apiVersion: apps/v1
kind: Deployment
metadata:
  name: example3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example3
  template:
    metadata:
      labels:
        app: example3
    spec:
      containers:
      - name: example3
        image: bekovkanat/example3:latest
        ports:
        - containerPort: 9001
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:Zxcvbnm123@host:5432/example3"

---
apiVersion: v1
kind: Service
metadata:
  name: example3-service
spec:
  type: NodePort
  selector:
    app: example3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
      nodePort: 30010  # Можно указать порт от 30000 до 32767